services:
    db:
        container_name: football-hub-db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - '5432:5432'

    frontend:
        container_name: football-hub-frontend
        build:
            context: .
            dockerfile: Dockerfile.frontend
            target: runner
        ports:
            - '4321:4321'
        restart: unless-stopped
        env_file:
            - .env
            - packages/frontend/.env
        depends_on:
            - db

volumes:
    postgres:
