services:
    db:
        container_name: football-hub-db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - '5432:5432'

    frontend:
        container_name: football-hub-frontend
        build:
            context: .
            dockerfile: Dockerfile.frontend
            target: runner
        ports:
            - '4321:4321'
        restart: unless-stopped
        env_file:
            - .env
            - packages/frontend/.env
        environment:
            BACKEND_API_HOST: http://backend:3000
        depends_on:
            - backend

    backend:
        container_name: football-hub-backend
        build:
            context: .
            dockerfile: Dockerfile.backend
            target: runner
        ports:
            - '3000:3000'
        restart: unless-stopped
        env_file:
            - .env
            - packages/backend/.env
        environment:
            CORS_ORIGINS: "http://frontend:4321"
            DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}"
        depends_on:
            - db

volumes:
    postgres:
